### ISSUE TITLE
Horario I1 viernes 14 septiembre

### ISSUE THREAD

**Issue by ctalvarez** [IIC2113-2018-2/syllabus#11]
Hola!
¿La i1 será en horario de clases o a las 18:30? Pregunto porque el viernes 14 muchos saldremos de Santiago y tenemos que planificar la salida.
Gracias

**Comment by nacosta-cl** [comment]
Creo que dijo que era en horario de clases

**Comment by negebauer** [comment]
es en horario de clases

**Comment by rasaffie** [comment]
Como dice el [programa del curso](https://github.com/IIC2113-2018-2/syllabus#interrogaciones) las interrogaciones serán en horario de clases.

**Comment by ctalvarez** [comment]
Gracias!
