### ISSUE TITLE
Duda número de transacciones

### ISSUE THREAD

**Issue by ifcarrera** [IIC2113-2018-2/syllabus#13]
Hola!
En la tarea, en al RF6, no logramos entender esto:

> la cantidad de transacciones no puede ser mayor o igual a la cantidad de personas en el grupo. 

A qué se refiere específicamente?

Saludos

**Comment by rasaffie** [comment]
Se refiere a que se debe cerrar el grupo con un mínimo de eficiencia: no hacer más transacciones que el número de personas en el grupo. Por ejemplo, en un grupo con las personas:

* _A_
* _B_ 
* _C_ 

en que los saldos son:

* _A_ le debe _X_ a _B_
* _A_ le debe _X_ a _C_
* _B_ le debe _X_ a _C_

lo esperado es que _A_ le pague _2X_ a _C_ directamente, y no que le pague a _B_ para que luego _B_ le pague a _C_.
