### ISSUE TITLE
Es necesario hacer login?

### ISSUE THREAD

**Issue by KatherineGuerrero** [IIC2113-2018-2/syllabus#14]
¿Es necesario hacerle login e inicio de sesión con contraseña? ¿O solo es como un libro de registro en que cualquiera que abra la aplicación puede ingresar pagos y cobros?

**Comment by sgvasquez** [comment]
No entiendo la diferencia entre ambos casos :c. Nosotros lo tenemos pensado más como una "aplicación web" donde los usuarios pueden conectarse a consultar sus datos/grupos/etc... ¿A que se refiere que sea como "la calculadora"?

**Comment by rasaffie** [comment]
Con la comparación me refería que la aplicación debe ser ideada como una herramienta que un sólo usuario utilizará en su computador para cuadrar cuentas. No es necesario que distintos usuarios tengan acceso a la aplicación de forma simultánea: un sólo usuario ingresa las transacciones asociadas a distintos correos de usuarios. Si otro usuario quiere consultar la información se podrá compartir a través de los archivos JSON y CSV para que cargue los datos en su propio computador.

**Comment by sgvasquez** [comment]
Gracias!
