### ISSUE TITLE
Robustez contra inputs

### ISSUE THREAD

**Issue by rihanuch** [IIC2113-2018-2/syllabus#17]
¡Hola!

¿Podemos asumir que los inputs entregados son válidos? :eyes: 
Por ejemplo que no se intentará agregar un usuario no existene a un grupo existente

¡Gracias!

**Comment by rasaffie** [comment]
El programa tiene que tener un mínimo de validez sobre los inputs. Respondiendo a tu ejemplo, no se puede caer si se intenta agregar un usuario que no existe a un grupo.
