### ISSUE TITLE
Duda Sobre Eliminación de Grupos 

### ISSUE THREAD

**Issue by nicosoto0** [IIC2113-2018-2/syllabus#18]
Estimados, 

 En el enunciado de la tarea se menciona que debe existir la funcionalidad de eliminar un Grupo. No nos queda claro si esto implica: cancela las deudas existentes de este grupo o si las deudas persisten de todas maneras.  

 Saludos

**Comment by rasaffie** [comment]
Cancela las deudas del grupo. Esto también se debe reflejar al consultar el balance entre 2 usuarios pertenecientes al grupo eliminado (que ya no tendrían esas transacciones).

**Comment by rihanuch** [comment]
¡Hola @rasaffie !

¿Entonces eso implica que los movimientos de los grupos también deben considerarse para ver el balance entre los dos?

¡Saludos! 😄

**Comment by rasaffie** [comment]
Eso queda a criterio de cada grupo: pueden considerar que las transacciones intermedias de un grupo no se reflejan en el balance entre 2 usuarios hasta que se cierra ese grupo, o pueden incluirlas siempre. Esto está relacionado con #19.
