### ISSUE TITLE
Actividad 2 - Contenidos / material

### ISSUE THREAD

**Issue by stephichau** [IIC2113-2018-2/syllabus#2]
Hola!

Hay alguna posibilidad de que suban el material/los contenidos que se evaluarán ?

Saludos.

**Comment by rasaffie** [comment]
Hola,

Los contenidos serán principalmente sobre los [principios S.O.L.I.D](https://en.wikipedia.org/wiki/SOLID). Tengo pensado subir el material mañana antes de la clase.

Saludos.
