### ISSUE TITLE
Pizzas Predefinidas

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2113-2018-2/syllabus#23]
Hola :)

Si me hago una pizza hecha a medida imitando a una predefinida (la hago idéntica a una Hawaiana, por ejemplo), ¿se debe cobrar el precio de la predefinida o el precio de la hecha a medida?

**Comment by rasaffie** [comment]
Hola,

El precio de la hecha a medida.

**Comment by fringlesinthestreet** [comment]
Gracias :)
