### ISSUE TITLE
Ingredientes con requisitos opuestos.

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2113-2018-2/syllabus#26]
Hola de nuevo,

Si tengo un ingrediente que sube la temperatura en 20º y otro que disminuye la temperatura en 20º. Al final, si una pizza tiene ambos ingredientes, ¿se queda en la temperatura base?

**Comment by fringlesinthestreet** [comment]
hola @rasaffie 

Los que existen ahora no poseen conflicto, pero me refería a si se agregaban ingredientes en un futuro. 

¿Entonces se puede asumir que **nunca** habrá conflicto?

**Comment by rasaffie** [comment]
Hola,

Con respecto a este tema pueden realizar el supuesto que prefieran para respaldar el diseño de su aplicación. De todas formas esto debe estar especificado en los documentos que entreguen.

**Comment by fringlesinthestreet** [comment]
Ok :),

Gracias!
