### ISSUE TITLE
Properties como decoradores

### ISSUE THREAD

**Issue by Okhan97** [IIC2113-2018-2/syllabus#27]
Hola,

Planeamos usar properties para la tarea, dado que los properties son en si decoradores, ¿cuenta el uso de estos como un patrón de diseño?

**Comment by rasaffie** [comment]
Hola,

Si bien las `properties` de Python son una implementación del patrón _Decorator_, uno de los objetivos de la tarea es que ustedes mismos implementen los patrones. Dicho esto, utilizar `properties` no contará como uno de los 3 patrones que deben aplicar y explicar su implementación.

Les recomiendo que revisen los ejemplos de código que aparecen en la página [Source Making](https://sourcemaking.com/) para ver qué adaptaciones deben realizar para implementar los patrones que detecten en el contexto de este problema.
