### ISSUE TITLE
Precio pizzas pre hechas

### ISSUE THREAD

**Issue by rihanuch** [IIC2113-2018-2/syllabus#28]
Hola!

Con nuestro grupo nos dimos cuenta que 3/5 pizzas cuestan 1000 menos que con los ingredientes. Podemos asumir que las otras 2 también? (Considerando que quizás fue un error) 😬 

Gracias!

**Comment by rasaffie** [comment]
No es un error, es solamente coincidencia.

**Comment by rihanuch** [comment]
Ok, muchas gracias! 😄
