### ISSUE TITLE
[Tarea3] Duda embase especial Palta

### ISSUE THREAD

**Issue by nicosoto0** [IIC2113-2018-2/syllabus#29]
Estimado, 

 No me queda la regla especia al agregar palta a una pizza. El "envase especial" que debe llevar la pizza como es: adicional a la caja en que se guarda la pizza o es el envase en que se guarda la misma pizza, en reemplazo a la caja. 

Mi duda es sobre todo en el caso del tener una Masa que modifica la caja, por ejemplo "Masa cruda", en el cual se debe tener una caja especial. ¿En este caso la pizza irá en una "caja especial para masa cruda" + "envasado especial de palta" sobre la caja por ejemplo?

Saludos!

**Comment by rasaffie** [comment]
El envase de la palta es un envase adicional a la caja de pizza. La idea es que al finalizar el pedido, en la sección de empaquetamiento de las instrucciones para preparar la pizza,  se le imprima al usuario la condición de masa cruda y que recuerde agregar la palta.
