### ISSUE TITLE
Patrones de diseño para la actividad de mañana

### ISSUE THREAD

**Issue by roy350** [IIC2113-2018-2/syllabus#3]
Hola! quería saber si en la actividad de mañana utilizaremos todos los patrones de diseño del libro o algunos en particular, para saber en cuales enfocarme en el estudio. Además saber si pudiera subir la clase de mañana para tener una mejor idea de estos. Muchas gracias!

**Comment by rasaffie** [comment]
Hola,

* Como dije en el anuncio pasado, la clase de hoy se enfocará en los 7 patrones de diseño estructurales.
* Para las próximas clases trataré de publicar las diapositivas con anticipación.

**Comment by roy350** [comment]
Muchas gracias profesor! que este bien
