### ISSUE TITLE
Contenidos I2

### ISSUE THREAD

**Issue by ctalvarez** [IIC2113-2018-2/syllabus#31]
Hola,

Cuál será el temario para la i2?
Saludos

**Comment by rasaffie** [comment]
Los contenidos que se evaluarán son los vistos desde la clase 5 hasta la clase 8, los que incluyen:

* Patrones de diseño (solamente los vistos en la clase 5)
* Frameworks y librerías
* Code Smells
* Refactoring
* Testing

Junto con el enunciado de la interrogación tendrán acceso a un resumen sobre patrones de diseño (como el que se entregó para la interrogación pasada), así como una lista con los nombres de los _code smells_ vistos en clases.

**Comment by javierlopeza** [comment]
> · Frameworks y librerías

¿Esto se refiere a la actividad opcional más la discusión que se hizo en clases de esta?

**Comment by rasaffie** [comment]
> > · Frameworks y librerías
> 
> ¿Esto se refiere a la actividad opcional más la discusión que se hizo en clases de esta?

Así es.

**Comment by roy350** [comment]
Alguna pagina recomendada, para el estudio de la parte de frameworks y librerias? o quizas subir la pauta de la actividad opcional? Muchas gracias!

**Comment by roy350** [comment]
Gracias!

**Comment by josemlira** [comment]
Hola! Para la parte de *Refactoring* será necesario saberse los nombres de las distintas técnicas y en qué consiste cada una? (Como los *code smells*)

**Comment by rasaffie** [comment]
> Hola! La parte de anti-patrones de la clase 6 entra también?

No, fue un comentario más que contenidos formales del curso.
