### ISSUE TITLE
Patrones: state vs strategy

### ISSUE THREAD

**Issue by jerosalazar** [IIC2113-2018-2/syllabus#32]
Hola, no me queda muy claro cual es la diferencia entre los patrones _state_ y _strategy_. Según entiendo, ambos ocupan un objeto para realizar una operación determinada y van cambiando este objeto de acuerdo a como cambian las necesidades de esa operación.

**Comment by rasaffie** [comment]
Estos patrones son similares porque modifican el comportamiento de un objeto a través de composición y delegación de objetos. Sin embargo algunas diferencias son:

* En el patrón _State_ las condiciones para cambiar el comportamiento están definidas en la implementación del patrón, mientras que para el patrón _Strategy_ el cliente puede modificar directamente la estrategia.
* En el patrón _State_ los estados en concreto guardan una referencia del objeto modificado para poder modificar el estado o interactuar con otros atributos/métodos de este. En el patrón _Strategy_ se modifica solamente la implementación de un algoritmo en concreto que no interactúa con el estado del objeto.

En resumen, el patrón _State_ modifica lo que **es** un objeto en base a su estado (el valor de sus atributos), mientras que el patrón _Strategy_ modifica **como** un algoritmo en particular se implementa, independientemente del estado del objeto.

Te recomiendo que leas en el libro GoF las descripción de los problemas que busca solucionar cada uno de estos patrones para entender la diferencia más allá de la implementación de cada uno. También puedes consultar [este enlace](https://stackoverflow.com/questions/1658192/what-is-the-difference-between-strategy-design-pattern-and-state-design-pattern) donde distintas personas plantean sus puntos de vista.

**Comment by jerosalazar** [comment]
Muchas gracias! me quedó bastante claro
