### ISSUE TITLE
Parallel Inheritance Hierarchies y Factory Method

### ISSUE THREAD

**Issue by cataherrera** [IIC2113-2018-2/syllabus#34]
Tengo una duda de que cuando uno usa factory method uno crea un Creator para un Product y despues uno crea ConcreteCreators para ConcreteProducts por lo tanto porque esto no seria el code smell de Parallel Inheritance Hierarchies? Si cada vez que quiero agregar una subclase ConcreteProduct tengo que crear una subclase ConcreteCreator

**Comment by rasaffie** [comment]
Es cierto que en el patrón _Factory Method_ hay una relación entre las jerarquías de _Creators_ y _Products_. Sin embargo, estas jerarquías no necesariamente son paralelas ni son de herencia:

* crear un _Concrete Product_ o un _Concrete Creator_ no implica crear una clase adicional en la otra jerarquía. Puede ser que un nuevo _Creator_ se relacione con _Products_ que ya existen (y viceversa).
* el patrón no necesariamente implica una jerarquía de herencia, ya que _Creator_ y _Product_ son interfaces de otras clases que pueden no presentar herencia.

Algo similar aplica para el patrón _Abstract Factory_, ya que si se agrega una _Concrete Factory_ también se debe agregar un _Product_ de cada tipo relacionado a esa _factory_. Esta relación es de cumplir con interfaces, por lo que no es directamente a lo que se refiere el _code smell Parallel Inheritance Hierarchies_, pero es cierto que también implica un grado de _Change Preventer_.

Frente a este último punto puedo comentar que los _code smells_ no son necesariamente un problema, dependen en el grado en que aparezcan y el contexto del problema. Para el caso de estos 2 patrones de diseño habría que ponderar los beneficios que agregan al encapsular lógica relacionada comparado con el acoplamiento entre clases que dificulta modificar el código.
