### ISSUE TITLE
Tarea 3: estados de los TODO

### ISSUE THREAD

**Issue by rihanuch** [IIC2113-2018-2/syllabus#35]
¡Hola! Me surgió una duda respecto a los estados de la tarea

¿Los estados de los __TODO__ son simplemente `Terminados` y `En proceso`, o se debe dar a elección que un estado se pueda cambiar a uno especificado? 🤔 

¡Gracias!

**Comment by rasaffie** [comment]
Son esos 2 estados, no se agregan de manera dinámica.

**Comment by rihanuch** [comment]
Ok, gracias! 😄
