### ISSUE TITLE
[RF8] Agrupación de ToDos

### ISSUE THREAD

**Issue by rihanuch** [IIC2113-2018-2/syllabus#38]
¡Hola!

Cuando se habla de agrupar, se refiere a filtrar los resultados, simplemente entregar un resumen del criterio mediante el cual se esta agrupando u otra cosa??

¡Muchas gracias! 😄

**Comment by rasaffie** [comment]
Se refiere a que los _TODOs_ se impriman agrupados en base a los distintos valores de cada categoría que permite la funcionalidad. Por ejemplo, un mismo usuario puede tener múltiples _TODOs_, por lo que se debería mostrar el nombre del usuario para luego listar información resumida de todos sus _TODOs_ (y así para todos los usuarios y sus _TODOs_).

**Comment by roy350** [comment]
me queda la duda con el requisito funcional 8, cuando dice:
RF8: Imprimir en consola un resumen de toda la lista de TODOs presentes. Esta funcionalidad debe permitir agruparlos según diferentes criterios:

por encargados
por categorías
por estados

Como los TODOs pueden tener mas de una categoria, como se mostraria si el usuario elige esta opcion, se repetirian todos?

**Comment by rasaffie** [comment]
En ese caso un _TODO_ con múltiples categorías aparecería bajo todas las categorías a la que pertenezca.
