### ISSUE TITLE
Interfaz de la aplicación

### ISSUE THREAD

**Issue by aaossa** [IIC2113-2018-2/syllabus#39]
Hay algún requisito sobre si la aplicación de TODOs de la tarea debe ser interactiva o por consola? Esto sería asumiendo el costo extra que significaría agregar persistencia en el caso de realizar la segunda opción. Agrego lo que me imagino por cada una.

```bash
# Interactiva
$ python3 todo.py
Ingrese un comando: 
# ...
```
```bash
# Consola
$ python3 todo.py add "Tarea 3" -category "Diseño"
# ...
```

**Comment by rasaffie** [comment]
No hay un requisito, pueden hacerlo como prefieran.

**Comment by aaossa** [comment]
Gracias!
