### ISSUE TITLE
Duda requisitos funcionales 1 y 2

### ISSUE THREAD

**Issue by roy350** [IIC2113-2018-2/syllabus#40]
Hola! me queda la duda con estos requisitos:
RF1: Agregar un TODO ingresando su título, fecha límite para realizarlo y una descripción.
RF2: Poder agregar múltiples TODOs con un sólo comando.

Es necesario implementarlos por separado, me refiero a que si en el menu deben estar las dos opciones o basta con que este la segunda opcion y si el cliente solo desea crear 1 TODO al finalizar la creacion de este que este decida salirse?

Además en el tema de la fecha limite, basta con dia, mes, año o tambien hora y minuto que se tiene para finalizar el TODO?

**Comment by rasaffie** [comment]
Hola,

1) No necesariamente se deben implementar por separado. Sin embargo, la idea de RF2 es que "con un sólo comando" se puedan agregar múltiples _TODOs_, lo que es diferente a ir agregandolos de a uno y decidir salirse. La forma de interacción y el formato de los parámetros lo pueden decidir ustedes, pero la idea de RF2 es que con una sola interacción se agreguen múltiples _TODOs_.
2) Pueden incluir el horario de la fecha límite si lo desean.

**Comment by roy350** [comment]
Además me queda la duda con el requisito funcional 8,cuando dice:
RF8: Imprimir en consola un resumen de toda la lista de TODOs presentes. Esta funcionalidad debe permitir agruparlos según diferentes criterios:

por encargados
por categorías
por estados

Como los TODOs pueden tener mas de una categoria, como se mostraria si el usuario elige esta opcion, se repetirian todos?

**Comment by roy350** [comment]
Profesor! con respecto a sus respuestas,
1. Al parecer no me quedo claro el requisto funcional 2, es que no entiendo bien como con un solo comando pueda crear mas de un TODO si necesito titulo, fecha limite, etc y estos parametros seran distintos para cada TODO, asi que por eso pense que se referia a que en un mismo "proceso" o iteracion se agregaran los TODO que el usuario quisiera.
2. Muchas gracias!

**Comment by rasaffie** [comment]
> Además me queda la duda con el requisito funcional 8,cuando dice:
> RF8: Imprimir en consola un resumen de toda la lista de TODOs presentes. Esta funcionalidad debe permitir agruparlos según diferentes criterios:
> 
> por encargados
> por categorías
> por estados
> 
> Como los TODOs pueden tener mas de una categoria, como se mostraria si el usuario elige esta opcion, se repetirian todos?

Por favor esta duda plantéala en el _issue_ https://github.com/IIC2113-2018-2/syllabus/issues/38

**Comment by rasaffie** [comment]
> 1. Al parecer no me quedo claro el requisto funcional 2, es que no entiendo bien como con un solo comando pueda crear mas de un TODO si necesito titulo, fecha limite, etc y estos parametros seran distintos para cada TODO, asi que por eso pense que se referia a que en un mismo "proceso" o iteracion se agregaran los TODO que el usuario quisiera.

Deben definir un formato para los parámetros de forma que permita ingresar esos 3 atributos para múltiples _TODOs_. Tienen flexibilidad en la forma que quieran implementar el ingreso de los datos: ya sea directamente a través de la línea de comando o con la ayuda de un archivo.

**Comment by roy350** [comment]
Osea por poner un ejemplo, bastaria con imprimir en consola esto?
``` Ingrese titulo, fecha limite y descripcion separandolos por comas y cada TODO con punto y coma```
y ahi el usuario dar un input del estilo
``` Tarea de Diseño detallado, 3 de diciembre, Tarea final; Tarea de arquitectura de computadores, 5 de diciembre, Tarea reprobatoria```

**Comment by rasaffie** [comment]
Sí, esa es una opción válida.
