### ISSUE TITLE
Testeando al rededor de  'if __name__ == "__main__"'

### ISSUE THREAD

**Issue by aaossa** [IIC2113-2018-2/syllabus#46]
Hola!

Dado que estoy haciendo mi aplicación por consola, tengo la siguiente línea como punto de entrada:

```python
if __name__ == "__main__":
    main()
```

A dicha función,[ `click` le agrega parámetros de forma dinámica](https://stackoverflow.com/a/49680253/3281097), por lo que, aunque la función los recibe, no es necesario que yo se los entregué ahí. Eso provoca que pylint me muestre el error `E1120: No value for argument '*' in function call (no-value-for-parameter)`, que deshabilito comentando `# pylint: disable=no-value-for-parameter` al final de la línea 2 del *snippet*.

Todo bien hasta que probé mis tests y la línea estaba marcada como "no cubierta" ya que no hay tests que pasen por ahí (lo que es obvio e intencionado). Probé evitando que se considerara en el *coverage* comentando `# pragma: no cover`, pero resulta que este comentario no es compatible con el de pylint, provocando que uno de los dos falle (probé colocando uno primero y luego el otro). La solución que logré fue agregar el comentario al final de la línea 1 del *snippet*.

Mis preguntas son:
* ¿Es válido lo que estoy haciendo al deshabilitar el *warning* de pylint en la línea 2?
* ¿Es válido si deshabilito el coverage en la línea 1?

El código resultante se ve así:

```python
if __name__ == "__main__": # pragma: no cover
    main() # pylint: disable=no-value-for-parameter
```

Gracias!

**Comment by rasaffie** [comment]
1) En este caso en particular tiene sentido modificar la configuración de `pylint`. Sin embargo debes detallar y explicar la razón en el _README.md_ de tu proyecto.
2) Tiene sentido no considerar la llamada a `main`como parte del `coverage` ya que no es parte del código fuente de la aplicación, si no que de cuando se utiliza.
