### ISSUE TITLE
[Tarea 1] Persistencia de los Datos

### ISSUE THREAD

**Issue by sgvasquez** [IIC2113-2018-2/syllabus#7]
Hola! Para la tarea, es necesario que los datos persistan entre llamadas a la aplicación? (usar una BD externa).

Gracias!

**Comment by rasaffie** [comment]
Hola,

No es necesario usar una base de datos externa. Sin embargo, si diseñan la interacción de su aplicación con los usuarios como comandos por consola independientes, deberán ofrecer persistencia de alguna manera para que un usuario pueda registrar más de una transacción. Si crean su aplicación como una consola interactiva esta persistencia sería a través de la memoria asignada al programa. 

También pueden llevar el registro en archivos JSON o CSV, considerando que la aplicación debe permitir exportar e importar estos.

**Comment by FarDust** [comment]
Saludos,

Si logramos esta persistencia a través de una base de datos en un contenedor de Docker. 
¿es necesario que se refleje esta decisión en alguno de los diagramas o en el README, aparte de las instrucciones de deploy?. 
Pensando que el funcionamiento de la aplicación debería ser igual fuera o dentro del contenedor dado su baja complejidad.

**Comment by rasaffie** [comment]
Utilizar una base de datos a través de un contenedor de Docker para resolver esta tarea es agregar complejidad innecesaria. Si de todas formas quieren hacerlo deben explicar y justificar sus desiciones de diseño (ya sea a través de los diagramas o del archivo README.md).

**Comment by roy350** [comment]
Hola, tengo una duda al respecto de la persistencia de los datos. Que diga que se puede hacer a través de archivos json o CSV quiere decir que tenemos que implementar ambas y darle al usuario la opción de elegir en que formato desea guardar y leer o solo implementamos uno? (en nuestro caso, implementamos json y se guarda/carga cada vez que se hace un cambio sobre los datos)
